import { readFile, writeFile } from 'node:fs/promises';
const IN='C:/Users/USER/Desktop/vb/3層/逃/逃生動線.gltf';
const OUT='C:/Users/USER/Desktop/coding/網頁/fire-golden-30s/models/routes-home.json';
const g=JSON.parse(await readFile(IN,'utf8'));
const acc=g.accessors, bvs=g.bufferViews, bufs=g.buffers;
const bufData=bufs.map(b=>{ if(!b.uri?.startsWith('data:')) throw new Error('external buffer'); return Buffer.from(b.uri.split(',')[1],'base64'); });
const readVec3=(ai)=>{ const a=acc[ai]; const bv=bvs[a.bufferView]; const buf=bufData[bv.buffer];
  const base=buf.byteOffset+(bv.byteOffset||0)+(a.byteOffset||0); const stride=bv.byteStride||12; const dv=new DataView(buf.buffer);
  const pts=[]; for(let i=0;i<a.count;i++){const o=base+i*stride; pts.push([+dv.getFloat32(o,true).toFixed(3),+dv.getFloat32(o+4,true).toFixed(3),+dv.getFloat32(o+8,true).toFixed(3)]);} return pts; };
let hasX=false; const routes=[];
g.nodes.forEach(n=>{ if(!(n.name&&n.name.startsWith('動線')))return; if(n.matrix||n.translation||n.rotation||n.scale)hasX=true;
  const c=g.nodes[n.children[0]]; if(c&&(c.matrix||c.translation||c.rotation||c.scale))hasX=true;
  routes.push({name:n.name, points:readVec3(g.meshes[c.mesh].primitives[0].attributes.POSITION)}); });
routes.sort((a,b)=>a.name.localeCompare(b.name));
console.log('hasTransform:',hasX); console.log(routes.map(r=>r.name+':'+r.points.length+'pts start='+JSON.stringify(r.points[0])+' end='+JSON.stringify(r.points.at(-1))).join('\n'));
await writeFile(OUT, JSON.stringify({routes})); console.log('-> wrote', OUT);
